
BASE_DEVICE_PATH := device/unihertz/jmax

PLATFORM_VERSION := 14
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)

PLATFORM_SECURITY_PATCH := 2024-07-05
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)

VENDOR_SECURITY_PATCH := 2024-09-05

-include device/unihertz/jmax/CommonBoardConfig.mk
